### ISSUE TITLE
openai>=1.0.0 compatibility

### ISSUE THREAD

**Issue by gurucharansrinivas** [voxel51/voxelgpt#108]
Using VoxelGPT with Openai>=1.0.0 results in following error;
 You tried to access openai.Moderation, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API. You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28` A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

Traceback (most recent call last): File "/fiftyone/default/__plugins__/@voxel51/voxelgpt/__init__.py", line 166, in execute for response in ask_voxelgpt_generator( File "/fiftyone/default/__plugins__/@voxel51/voxelgpt/voxelgpt.py", line 250, in ask_voxelgpt_generator if not moderate_query(query): File "/fiftyone/default/__plugins__/@voxel51/voxelgpt/links/query_moderator.py", line 14, in moderate_query return get_moderator().run(query) File "/usr/local/lib/python3.8/dist-packages/langchain/chains/base.py", line 505, in run return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[ File "/usr/local/lib/python3.8/dist-packages/langchain/chains/base.py", line 310, in __call__ raise e File "/usr/local/lib/python3.8/dist-packages/langchain/chains/base.py", line 304, in __call__ self._call(inputs, run_manager=run_manager) File "/usr/local/lib/python3.8/dist-packages/langchain/chains/moderation.py", line 93, in _call results = self.client.create(text) File "/usr/local/lib/python3.8/dist-packages/openai/_utils/_proxy.py", line 22, in __getattr__ return getattr(self.__get_proxied__(), attr) File "/usr/local/lib/python3.8/dist-packages/openai/_utils/_proxy.py", line 43, in __get_proxied__ return self.__load__() File "/usr/local/lib/python3.8/dist-packages/openai/lib/_old_api.py", line 33, in __load__ raise APIRemovedInV1(symbol=self._symbol) openai.lib._old_api.APIRemovedInV1: You tried to access openai.Moderation, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API. You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28` A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

**Comment by jacobmarks** [comment]
Hey @gurucharansrinivas , sorry you ran into this issue!

When OpenAI released the 1.0.0 version of their Python library, they made some breaking changes to the API. For the time being, we have pinned the OpenAI version in our `requirements.txt` file [here](https://github.com/voxel51/voxelgpt/blob/main/requirements.txt). It should work if you use a compatible version :)
